baseURL = "https://opendatasoft.github.io/codelibrary/"
languageCode = "en-us"
title = "Codelibrary"

[taxonomies]
  category = "categories"
  tag = "tags"

## Add JSON output for search
[outputs]
  home = ["HTML", "RSS", "JSON"]
