baseURL = "https://opendatasoft.github.io/codelibrary/"
languageCode = "en-us"
title = "Codelibrary"


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]