baseURL = "https://codelibrary.opendatasoft.com"
languageCode = "en-us"
title = "Codelibrary"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "permalink"]
params = ["categories", "tags"]

[outputs]
  home = ["HTML", "RSS", "Algolia"]

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/bulma"
    target = "assets/scss/bulma"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true