baseURL = "https://codelibrary.opendatasoft.com"
languageCode = "en-us"
title = "Codelibrary"

sectionPagesMenu = "main"

[taxonomies]
  tag = "tags"

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.algolia]
vars = ["title", "description", "content", "section", "permalink", "relpermalink"]
params = ["section", "tags"]

[outputs]
  home = ["HTML", "RSS", "Algolia"]

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/bulma"
    target = "assets/scss/bulma"
