backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: Resources # Used in routes, e.g., /admin/collections/blog
    label: Resources # Used in the UI
    label_singular: Resource
    folder: "content" # The path to the folder where the documents are stored
    path: "content/{{fields.section}}/{{field.page}}/{{field.order}}"
    create: true # Allow users to create new documents in this collection
    nested:
      depth: 5
    media_folder: "{{fields.section}}/{{field.page}}/{{field.order}}"
    public_folder: "{{fields.section}}/{{field.page}}/{{field.order}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: hidden
      - label: Url
        name: url
        required: false
        widget: string
        pattern: [
          '/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)/',
          'Not a valid URL'
        ]
      - label: Height
        name: height
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
      - label: HTML
        name: html
        widget: file
        default_language: html
        index_file: 'html.inc'
      - label: CSS
        name: css
        widget: file
